### ISSUE TITLE
Feature: .toString() off of pagination()

### ISSUE THREAD

**Issue by bmitchinson** [felixmosh/knex-paginate#12]
Previously we were testing that queries worked by asserting their generated SQL query output. I've noticed that using pagination doesn't allow for a .toString() option.

This observation that ".toString()" isn't available is true right? If so maybe I could work on a PR for it? Would be helpful from a testing perspective, but also for debugging I believe.

**Comment by felixmosh** [comment]
PR's are always welcome :]
Because of the fact that under the hood it should execute a count of all that means that it may execute 2 queries.
In order to do that, it converts the given query to a transaction query of 2 queries.

There is no meaning of `toString` on the transaction.
But if you will make any improvement, I will be more then happy to review your solution.

BTW, the lib propagates the `debug` method, maybe it will be useful for you.

**Comment by felixmosh** [comment]
In active issue, closing for now.

If you want to work on it, pls re-open
