### ISSUE TITLE
pagination.total in result is actually string

### ISSUE THREAD

**Issue by grebenyukov** [felixmosh/knex-paginate#2]
Hi Felix!

Thank you for your package!
Is it intended or error that pagination.total is actually string, not number in result?

```
    "pagination": {
        "total": "806792",
        "lastPage": 26894,
        "perPage": 30,
        "currentPage": 1,
        "from": 0,
        "to": 30
    }
```

**Comment by felixmosh** [comment]
Thanx for reporting this issue, will be fixed soon.

**Comment by felixmosh** [comment]
@grebenyukov I've checked it, it looks like this is related to the driver that you are using.

Cause MySql (the driver  that I'm  using) converts it properly. 

![image](https://user-images.githubusercontent.com/9304194/73153938-4ef7c700-40de-11ea-95b1-222f5a2189b3.png)
And, there is a test for this.
https://github.com/felixmosh/knex-paginate/blob/master/__tests__/index.spec.js#L185

Anyway fixed in the code
